### ISSUE TITLE
URDF files used to generate ikfast

### ISSUE THREAD

**Issue by chjohnkim** [yijiangh/ikfast_pybind#8]
Hi, is there any way you could share the URDF files you used to generate the ikfast cpp solutions (particularly UR5)? I'm trying to use the repo but haven't found the right URDF that corresponds to the ikfast solution. Thanks!

**Comment by yijiangh** [comment]
@chjohnkim Hi! I get them from https://github.com/ros-industrial/universal_robot

In case you still find them not matching, the ROS Industrial developers maintain this IKFast generated [cpp file](https://github.com/ros-industrial/universal_robot/blob/melodic-devel/ur_kinematics/src/ur_kin.cpp). You can drop it here and build the binding yourself. I recently did that for [UR5e](https://github.com/yijiangh/ikfast_pybind/tree/master/src/ur5e).
